### ISSUE TITLE
Clarification needed on purpose, documentation, etc.

### ISSUE THREAD

**Issue by Groebehavn** [kroshu/ros2_kuka_sunrise_interfaces#3]
There is no information on what this repo stands for. At least not from far. What service messages are listed here? What we use these for? Consider this repo in the reorganization issue as well please.

**Comment by resizoltan** [comment]
This package will be moved to the [ros2_kuka_sunrise](https://github.com/kroshu/ros2_kuka_sunrise/tree/feature/prepare-for-open-collab) repo. There is a standard understanding of packages ending with _interfaces in ROS2, but stating its purpose explicitly cannot hurt either.

**Comment by Groebehavn** [comment]
Yes, the _interface part, for sure, but the contained messages are not self-descriptive. I would still suggest to have a little help here.

**Comment by resizoltan** [comment]
I added a short description to each srv type. I think that should be enough since the messages themselves are quite general. We will see how they evolve in the future and how specific they will get.
See: [kuka_sunrise_interfaces/srv](https://github.com/kroshu/ros2_kuka_sunrise/tree/feature/prepare-for-open-collab/kuka_sunrise_interfaces/srv)

**Comment by kovacsge11** [comment]
Moved to ros2__kuka_sunrise repo.
